# Generated by Django 4.2.30 on 2026-06-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_organization_enable_ai_personalization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='brand_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='unsubscribe_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='unsubscribe_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
