# Generated by Django 5.0.14 on 2026-07-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_organization_enable_ai_personalization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='custom_tracking_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
