# Generated by Django 5.0.14 on 2026-06-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_organization_enable_ai_personalization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="report_emails",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of emails to receive reports",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="report_schedule",
            field=models.CharField(
                choices=[("DAILY", "Daily"), ("WEEKLY", "Weekly"), ("NONE", "None")],
                default="NONE",
                max_length=10,
            ),
        ),
    ]
