# Generated by Django 5.0.14 on 2026-06-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0007_manualtask"),
        ("campaigns", "0008_merge_20260610_2213"),
    ]

    operations = []
