# Generated by Codex on 2026-06-11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0008_merge_20260610_2213"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVariant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("variant_label", models.CharField(max_length=10)),
                ("subject", models.TextField()),
                ("body", models.TextField()),
                ("weight", models.PositiveIntegerField(default=50)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.organization",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="campaigns.sequencestep",
                    ),
                ),
            ],
            options={
                "ordering": ["variant_label"],
                "unique_together": {("step", "variant_label")},
            },
        ),
        migrations.AddField(
            model_name="campaignlead",
            name="last_email_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_campaign_leads",
                to="campaigns.emailvariant",
            ),
        ),
    ]
