# Generated by Django 4.2.30 on 2026-06-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_cached_counters'),
        ('campaigns', '0009_campaignlead_bounce_metadata'),
    ]

    operations = [
    ]
