# Generated by Django 5.0.14 on 2026-08-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_custom_mailbox_security_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencestep',
            name='use_ai',
            field=models.BooleanField(default=False),
        ),
    ]
