# Generated by Django 5.0.14 on 2026-07-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_custom_mailbox_security_updates'),
        ('tenants', '0002_organization_enable_ai_personalization_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['organization', 'status'], name='campaign_org_status_idx'),
        ),
    ]
