# Generated by Django 5.0.14 on 2026-07-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_custom_mailbox_security_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedemailaccount',
            name='status',
            field=models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected')], default='CONNECTED', max_length=20),
        ),
    ]
