# Generated by Django 5.0.14 on 2026-07-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_custom_mailbox_security_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlead',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent message/call actually sent to the lead on this campaign.', null=True),
        ),
    ]
