# Generated by Django 5.0.14 on 2026-08-13 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_custom_mailbox_security_updates'),
        ('tenants', '0002_organization_enable_ai_personalization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_tasks', to='campaigns.campaignlead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_tasks', to='campaigns.sequencestep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaignlead',
            name='waiting_on_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_leads', to='campaigns.manualtask'),
        ),
    ]
