# Generated by Django 5.0.14 on 2026-07-04 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_custom_mailbox_security_updates'),
        ('tenants', '0002_organization_enable_ai_personalization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceStepEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_order', models.IntegerField()),
                ('channel_type', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('SENT', 'Sent'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked'), ('REPLIED', 'Replied')], max_length=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_events', to='campaigns.campaign')),
                ('campaign_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_events', to='campaigns.campaignlead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'step_order', 'event_type'], name='campaigns_s_campaig_2f9f42_idx')],
            },
        ),
    ]
