# Generated by Django 5.0.14 on 2026-07-08 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_custom_mailbox_security_updates'),
        ('leads', '0005_merge_0004_leadimportjob_0004_tag_color'),
        ('tenants', '0002_organization_enable_ai_personalization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribeFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_feedbacks', to='leads.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
