# Generated by Django 5.0.14 on 2026-06-18 02:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
        ("tenants", "0002_organization_enable_ai_personalization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="custom_variables",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                default="#6366f1",
                help_text="Hex color code for the tag badge, e.g. #6366f1",
                max_length=7,
            ),
        ),
        migrations.CreateModel(
            name="LeadImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=255)),
                ("total_rows", models.IntegerField(default=0)),
                ("imported_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("error_log", models.JSONField(blank=True, default=list)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockedDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_domains",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["domain"],
                "unique_together": {("domain", "organization")},
            },
        ),
    ]
