# Generated by Django 5.0.14 on 2026-06-10 10:15

import leads.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=leads.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='custom_data',
            field=leads.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=leads.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=leads.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='linkedin_url',
            field=leads.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=leads.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
