# Generated by Django 5.0.14 on 2026-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_company_alter_lead_custom_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='crm_external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='crm_source',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='crm_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
