# Generated by Django 5.0.14 on 2026-06-29 11:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_custom_mailbox_security_updates'),
        ('leads', '0005_merge_0004_leadimportjob_0004_tag_color'),
        ('tenants', '0002_organization_enable_ai_personalization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEngagementEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('EMAIL_SENT', 'Email Sent'), ('EMAIL_OPENED', 'Email Opened'), ('LINK_CLICKED', 'Link Clicked'), ('EMAIL_REPLIED', 'Email Replied'), ('EMAIL_BOUNCED', 'Email Bounced'), ('SMS_SENT', 'SMS Sent'), ('CALL_INITIATED', 'Call Initiated'), ('UNSUBSCRIBED', 'Unsubscribed')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_events', to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to='leads.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.organization')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['lead', 'occurred_at'], name='leads_leade_lead_id_a74ba4_idx'), models.Index(fields=['campaign', 'occurred_at'], name='leads_leade_campaig_373af2_idx'), models.Index(fields=['event_type', 'occurred_at'], name='leads_leade_event_t_12ad23_idx')],
            },
        ),
    ]
